tap "abtris/tap", "git@github.com:abtris/homebrew-tap.git", trusted: true
tap "adoptopenjdk/openjdk", trusted: true
tap "anomalyco/tap", trusted: true
tap "bufbuild/buf", trusted: true
tap "buo/cask-upgrade", trusted: true
tap "ctrlspice/otel-desktop-viewer", "https://github.com/CtrlSpice/homebrew-otel-desktop-viewer", trusted: true
tap "cue-lang/tap", trusted: true
tap "cuelang/tap", trusted: true
tap "dagger/tap", trusted: true
tap "danielfoehrkn/switch", trusted: true
tap "datawire/blackbird", trusted: true
tap "encoredev/tap", trusted: true
tap "equinix-labs/otel-cli", trusted: true
tap "goreleaser/tap", trusted: true
tap "hashicorp/tap", trusted: true
tap "heroku/brew", trusted: true
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "k8sgpt-ai/k8sgpt", trusted: true
tap "kylef/formulae", trusted: true
tap "mingrammer/flog", trusted: true
tap "reviewdog/tap", trusted: true
tap "warrensbox/tap", trusted: true
tap "withgraphite/tap", trusted: true
brew "asciinema"
brew "atuin"
brew "aws-iam-authenticator"
brew "awscli"
brew "libgit2"
brew "bat"
brew "caddy"
brew "cocoapods"
brew "colordiff"
brew "comby"
brew "deno"
brew "dog"
brew "doppler"
brew "exercism"
brew "sdl2-compat"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "betterleaks"
brew "git-secrets"
brew "git-town"
brew "gitui"
brew "gitup"
brew "glow"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "grpcurl"
brew "gum"
brew "helix"
brew "herdr"
brew "ncurses"
brew "htop"
brew "httpie"
brew "hugo"
brew "hunk"
brew "imagemagick"
brew "jj"
brew "jq"
brew "k6"
brew "k9s"
brew "kotlin"
brew "kotlin-language-server"
brew "kubernetes-cli"
brew "lazygit"
brew "lefthook"
brew "leiningen"
brew "lsd"
brew "mage"
brew "mame"
brew "mcfly"
brew "midnight-commander"
brew "miller"
brew "mise"
brew "mkcert"
brew "mongosh"
brew "mpv"
brew "neovim"
brew "tree-sitter-cli"
brew "nvm"
brew "ocproxy"
brew "opa"
brew "openapi-generator"
brew "openconnect"
brew "p7zip"
brew "pandoc"
brew "pi-coding-agent"
brew "pipenv"
brew "pkgconf"
brew "postgresql@12", restart_service: :changed
brew "python@3.9"
brew "rbenv"
brew "ripgrep"
brew "smartmontools"
brew "starship"
brew "tctl", link: false
brew "teleport"
brew "temporal"
brew "terragrunt"
brew "terramate"
brew "testkube"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "trippy"
brew "vale"
brew "vcprompt"
brew "vhs"
brew "wget"
brew "youtube-dl"
brew "zellij"
brew "zig"
brew "zoxide"
brew "zsh-autosuggestions"
brew "abtris/tap/gab"
brew "abtris/tap/zotero-mcp-go-server"
brew "anomalyco/tap/opencode"
brew "bufbuild/buf/buf"
brew "dagger/tap/dagger"
brew "danielfoehrkn/switch/switch"
brew "equinix-labs/otel-cli/otel-cli"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/waypoint"
brew "k8sgpt-ai/k8sgpt/k8sgpt"
brew "mingrammer/flog/flog"
brew "reviewdog/tap/reviewdog"
brew "withgraphite/tap/graphite"
cask "audacity"
cask "aws-vault-binary"
cask "basictex"
cask "blackhole-16ch"
cask "cmux"
cask "codex"
cask "ctrlspice/otel-desktop-viewer/otel-desktop-viewer"
cask "darktable"
cask "fluidvoice"
cask "flutter"
cask "font-3270-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "gitbutler"
cask "goreleaser/tap/goreleaser"
cask "librecad"
cask "macfuse"
cask "podman-desktop"
cask "quarto"
cask "warrensbox/tap/tfswitch"
cask "wezterm"
cask "zed"
go "github.com/air-verse/air"
go "github.com/spf13/cobra-cli"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/ramya-rao-a/go-outline"
go "github.com/golangci/golangci-lint/cmd/golangci-lint"
go "golang.org/x/lint/golint"
go "github.com/fatih/gomodifytags"
go "github.com/uudashr/gopkgs/v2/cmd/gopkgs"
go "github.com/haya14busa/goplay/cmd/goplay"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/koron/iferr"
go "github.com/josharian/impl"
go "github.com/deepmap/oapi-codegen/cmd/oapi-codegen"
go "honnef.co/go/tools/cmd/staticcheck"
go "github.com/google/wire/cmd/wire"
go "github.com/hybridgroup/yzma"
npm "@google/gemini-cli"
npm "tailwindcss"
