#!/bin/bash
set -e
# INSTALL MacOS X
if test ! $(which gcc); then
  echo "Installing command line developer tools..."
  xcode-select --install
fi

if test ! $(which brew); then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Updating Homebrew..."
brew update

tools=(
  ansible
  awscli
  bash
  curl
  dnsmasq
  gettext
  git
  go
  font-fira-code
  hugo
  httpie
  jq
  jsonnet
  mas
  netcat
  node
  nvm
  openssl
  pipenv
  python
  qnapi
  rbenv
  redis
  sqlite
  telnet
  terraform
  thefuck
  tree
  vim
  wget
  zsh
  zsh-autosuggestions
  zsh-syntax-highlighting
)

echo "Installing tools..."
brew install ${tools[@]}

apps=(
  iterm2
  visual-studio-code
)

echo "Cleaning Homebrew..."
brew cleanup

apps_ids=(
  946399090 # Telegram Lite (2.2.0)
  1278508951 # Trello (2.11.7)
  406056744 # Evernote (7.14)
  595191960 # CopyClip (1.9.6)
  1091189122 # Bear (1.7.16)
  803453959 # Slack (4.9.0)
  568494494 # Pocket (1.8.5)
  1147396723 # WhatsApp (2.2037.6)
  1289197285 # MindNode (7.3.3)

)

echo "Installing apps from Mac App Store..."
mas install ${apps_ids[@]}

# make symlinks
ln -s ~/bin/dotfiles/profile ~/.profile
ln -s ~/bin/dotfiles/zshrc-ohmyzsh ~/.zshrc
# make dir (default not exists)
mkdir ~/.ssh
ln -s ~/bin/dotfiles/ssh/config ~/.ssh/config
# iterm2 settings
ln -s ~/bin/dotfiles/git/.gitconfig ~/.gitconfig
ln -s ~/bin/dotfiles/git/.gitignore ~/.gitignore
ln -s ~/bin/dotfiles/git/.gittemplate ~/.gittemplate
ln -s ~/bin/dotfiles/git/.git-commit-template.txt ~/.git-commit-template.txt
# change shell
csh -s /bin/zsh
source ~/.profile
zsh
